services:
  backend:
    build:
      context: ./self-hosted-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: on-failure

  excalidraw:
    build:
      context: .
    container_name: excalidraw
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure
